In [ ]:
import numpy as np

..
[[ 0.02237472 -0.11432729 -1.08018027 -0.6278428 ]
 [-0.26418598 -1.24576166 -0.0815577   0.10285879]
 [-1.72355795 -1.74204141 -0.33027124  0.3218475 ]
 [-0.29209782  1.967935   -1.8049533  -0.03896993]
 [-1.21290966  2.42082895 -0.61033071  0.17751608]
 [ 2.5653752   0.35985143 -0.8904237   0.21484749]
 [ 2.42263852  0.72088539  0.01346993 -0.68318692]
 [-0.25984989  1.41612212  0.93930059  1.48849413]
 [-1.14424263  2.2232347  -0.41287021 -0.29829725]
 [-0.51609234 -0.58310758 -1.27198776 -1.6643528 ]]
[[ 0.02237472 -0.11432729 -1.08018027 -0.6278428 ]
 [-0.26418598 -1.24576166 -0.0815577   0.10285879]]
